spring:
  application:
    name: tf2025

proxy:
  kafka:
    enabled: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic: ${KAFKA_TOPIC:um.tf2025.demo}
  redis:
    enabled: true
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
