server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: 192.168.194.250:9092
    consumer:
      group-id: tf25-proxy
      auto-offset-reset: earliest

tf25:
  backend:
    base-url: http://localhost:8080
  catedra:
    base-url: http://192.168.194.250:8080

kafka:
  topic:
    eventos: NOMBRE_DEL_TOPIC_REAL
