spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tf25
    username: tf25
    password: tf25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    org.springframework: INFO

tf25:
  kafka:
    topic:
      ventas: ${TF25_KAFKA_TOPIC_VENTAS:ventas-confirmadas}
  venta:
    exigir-bloqueos: false
  proxy:
    # m치s adelante va a apuntar al servicio proxy de la c치tedra
    base-url: http://localhost:8081
  sync:
    # cada cu치nto se sincronizan eventos autom치ticamente (ms)
    fixed-delay-ms: 60000
